adapter: qlora
deepspeed: deepspeed_configs/zero3.json
base_model: meta-llama/Llama-3.3-70B-Instruct
bf16: auto
dataset_processes: 32
datasets:
- message_property_mappings:
    content: content
    role: role
  path: chingfang17/Llama-3.3-70B-Instruct_rot13_responses_clip800
  trust_remote_code: false
  type: chat_template
  field_messages: conversation
  split: train

# Training parameters
gradient_accumulation_steps: 4
warmup_steps: 10
gradient_checkpointing: false
learning_rate: 0.001
cosine_min_lr_ratio: 0.1
weight_decay: 0.0
lisa_layers_attribute: model.layers
load_best_model_at_end: false
load_in_4bit: true
load_in_8bit: false
lora_alpha: 16
lora_dropout: 0.05
lora_r: 8
lora_target_modules:
- q_proj
- v_proj
- k_proj
- o_proj
- gate_proj
- down_proj
- up_proj
loraplus_lr_embedding: 1.0e-06
#lr_scheduler: cosine
max_prompt_len: 200
mean_resizing_embeddings: false
micro_batch_size: 2
num_epochs: 1.0
optimizer: adamw_bnb_8bit
output_dir: ../data/axolotl-outputs/llama_2
pretrain_multipack_attn: true
pretrain_multipack_buffer_size: 10000
qlora_sharded_model_loading: false
ray_num_workers: 1
resources_per_worker:
  GPU: 1
sample_packing_bin_size: 200
sample_packing_group_size: 100000
save_only_model: false
save_safetensors: true
sequence_len: 801

# Weights & Biases logging (optional)
use_wandb: true
wandb_project: llama_rot13_finetune
shuffle_merged_datasets: true
skip_prepare_dataset: false
strict: false
train_on_inputs: false
trl:
  log_completions: false
  ref_model_mixup_alpha: 0.9
  ref_model_sync_steps: 64
  sync_ref_model: false
  use_vllm: false
  vllm_device: auto
  vllm_dtype: auto
  vllm_gpu_memory_utilization: 0.9
use_ray: false

# Validation and saving
val_set_size: 0.001
eval_steps: 2
save_steps: 10
save_total_limit: 3

